import { Metadata } from 'next'
import ClientsSection from '@/components/sections/ClientsSection'
import { Navbar } from '@/components/sections/Navbar'
import { Footer } from '@/components/sections/Footer'
import { StickyCTA } from '@/components/sections/StickyCTA'

export const metadata: Metadata = {
  title: 'Klien & Lembaga Pengguna ELFAN System | 228 Institusi: Sekolah, Universitas, Pemerintah',
  description: 'Solusi literasi digital terpercaya untuk 228 institusi: 23 Perpustakaan Daerah Sulawesi Selatan, 7 Universitas (UNISSULA, IAIN, UMKT), 126 Sekolah, dari SD/MI hingga Instansi Pemerintah. Mendukung transformasi digital pelayanan publik dan pendidikan.',
  keywords: [
    'klien elfan system',
    'lembaga pengguna perpustakaan digital',
    'sekolah negeri pengguna bookless library',
    // Sulawesi Selatan (MASSIVE - 96 schools + 32 government libraries!)
    'perpustakaan digital sulawesi selatan',
    'bookless library sulawesi selatan',
    'perpustakaan daerah sulawesi selatan',
    'dinas perpustakaan sulawesi selatan',
    'dpk sulawesi selatan',
    'perpustakaan digital pemerintah',
    'aplikasi perpustakaan daerah',
    'solusi smart city literasi',
    'perpustakaan digital instansi pemerintah',
    'transformasi digital perpustakaan daerah',
    'perpustakaan digital makassar',
    'bookless library sma negeri makassar',
    'sma negeri 1 makassar',
    'sma negeri 2 makassar',
    'perpustakaan digital bone',
    'bookless library bone',
    'smk negeri bone digital library',
    'perpustakaan digital takalar',
    'sma negeri takalar',
    'perpustakaan digital toraja utara',
    'perpustakaan digital soppeng',
    'perpustakaan digital jeneponto',
    'perpustakaan digital bulukumba',
    'perpustakaan digital maros',
    'perpustakaan digital parepare',
    'perpustakaan digital luwu',
    'perpustakaan offline sulawesi',
    'digital library tanpa internet',
    'inovasi literasi sekolah sulawesi',
    'perpustakaan digital daerah terpencil',
    'dominasi digital sulawesi selatan',
    // Jawa Barat
    'perpustakaan digital bogor',
    'bookless library bandung',
    'pesantren digital bekasi',
    'islamic center wadi mubarak',
    'mimbarul huffadz bekasi',
    // Jawa Tengah (UPDATED - Universitas)
    'perpustakaan digital solo',
    'bookless library solo',
    'perpustakaan digital universitas',
    'digital library unissula',
    'perpustakaan iain surakarta',
    'perpustakaan uin raden mas said',
    'perpustakaan iain purwokerto',
    'perpustakaan uin saizu',
    'stie swastamandiri',
    'perpustakaan digital kampus',
    'smk negeri 1 surakarta',
    'smk negeri 5 surakarta',
    'smk negeri 6 surakarta',
    'perpustakaan digital sragen',
    'smk negeri sragen',
    'smk muhammadiyah sragen',
    'perpustakaan digital karanganyar',
    'perpustakaan digital sukoharjo',
    'perpustakaan digital klaten',
    'perpustakaan digital diy',
    'perpustakaan digital sleman',
    'sdit luqman al hakim sleman',
    'smk negeri jawa tengah',
    'perpustakaan digital smk',
    'bookless library karanganyar',
    'pesantren digital sukoharjo',
    'al-mukmin ngruki',
    'stiq isykarima',
    'idbc solo',
    'pesantren digital sragen',
    // Jakarta & Bekasi (NEW)
    'perpustakaan digital jakarta',
    'sdit qotrunnada',
    'perpustakaan digital bekasi',
    'ma as-syafiiah bekasi',
    'mts fisabilillah bekasi',
    // Jawa Timur (UPDATED - Surabaya & Malang)
    'perpustakaan digital malang',
    'bookless library surabaya',
    'perpustakaan digital surabaya',
    'sma muhammadiyah 10 surabaya',
    'alif laam mim surabaya',
    'mi darul quran malang',
    'pesantren digital jombang',
    'bahrul ulum jombang',
    'pesantren digital sidoarjo',
    // Sumatera (UPDATED - UIN SUSKA)
    'perpustakaan digital riau',
    'bookless library lampung',
    'perpustakaan digital batam',
    'perpustakaan digital bangka belitung',
    'smp bahrul huda bangka',
    'sma negeri kandis siak',
    'perpustakaan digital kepulauan',
    'perpustakaan uin suska riau',
    'fakultas syariah hukum uin riau',
    'perpustakaan digital universitas riau',
    // Kalimantan (UPDATED - UMKT & UMB)
    'perpustakaan digital balikpapan',
    'bookless library kalimantan timur',
    'smait al-auliya balikpapan',
    'perpustakaan umkt',
    'perpustakaan universitas muhammadiyah kalimantan timur',
    'perpustakaan umb banjarmasin',
    'perpustakaan digital universitas kalimantan',
    'digital library umkt',
    // Bali
    'perpustakaan digital bali',
    'yasmaiba bali',
    // Jakarta (UPDATED)
    'perpustakaan digital jakarta',
    'istana quran indonesia',
    'sdit jakarta',
    // Internasional
    'perpustakaan digital malaysia',
    'bookless library malaysia',
    // General
    'klien perpustakaan digital indonesia',
    'institusi pengguna elfan system',
    'sekolah negeri digital indonesia',
    'pesantren digital nusantara',
    'perpustakaan digital offline',
    'solusi literasi tanpa kuota',
    'perpustakaan digital sdit',
    'perpustakaan digital mi',
    'perpustakaan digital sd',
    'perpustakaan digital smp',
    'perpustakaan digital mts',
    'perpustakaan digital sma',
    'perpustakaan digital ma',
    'perpustakaan digital smk',
    'bookless library smk negeri',
    'perpustakaan digital perguruan tinggi',
    'perpustakaan digital universitas',
    'digital library kampus',
    'perpustakaan kampus offline',
    'solusi literasi universitas',
    'perpustakaan digital akademis',
    'perpustakaan digital pemerintah daerah',
    'perpustakaan daerah digital',
    'government certified solution',
  ],
  openGraph: {
    title: 'Klien & Lembaga Pengguna ELFAN System | 228 Institusi: Sekolah, Universitas, Pemerintah',
    description: '23 Perpustakaan Daerah, 7 Universitas, 126 Sekolah. Mitra transformasi digital pelayanan publik dan pendidikan di seluruh Indonesia.',
    url: 'https://www.elfanbookless.com/klien',
    siteName: 'ELFAN System',
    locale: 'id_ID',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Klien & Lembaga Pengguna ELFAN System',
    description: '228 Institusi: Sekolah, Universitas, 23 Perpustakaan Daerah',
  },
}

export default function KlienPage() {
  return (
    <main className="min-h-screen">
      <Navbar />
      <ClientsSection />
      <Footer />
      <StickyCTA />
    </main>
  )
}
